# Generated by Django 4.2.5 on 2023-09-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
